### PR TITLE
KISS, DRY, PEP8

### PR DESCRIPTION
**Pull request by freko247**
Cleaned up the script a bit, fixed imports, added missing whitespaces, string formatting and some other stuff, to make the code a bit easier to read.

### CODE REVIEW

**Comment by trevorndodds** [comment]
Thanks, I gave it a quick test but it fails to run. Have you tested it on your side?

**Comment by freko247** [comment]
Hey @trevorndodds, it runs in my environment. Did you notice that I removed the port variable, ie. the port should be a part of the server url.

**Comment by trevorndodds** [comment]
That did it, I have to enter the full URL. Also you removed the timestring from the index name. I prefer to roll my indexes (daily/monthly) and have the flexibility with curator.

**Comment by freko247** [comment]
@trevorndodds that makes sense, I've only used ES for indexing finite amounts of data previously, so I haven't used a curator before.

**Comment by freko247** [comment]
I updated my pr, so now it uses the time period identifier for indexes.

**Comment by trevorndodds** [comment]
Thanks! I made a small update _ to - between the index name and date.

**Pull request merged**
